name: CI/CD Pipeline

on: [push]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dpkg-dev

      - name: Build and package
        run: |
          make package

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: prime-checker-deb
          path: ./*.deb